CREATE TABLE Motor (
    SPLIT TEXT NOT NULL,
    DATASET TEXT NOT NULL,
    ENGINE_ID INTEGER NOT NULL,
    CYCLE INTEGER NOT NULL,
    setting_1 NUMERIC,
    setting_2 NUMERIC,
    setting_3 NUMERIC,
    sensor_1 NUMERIC,
    sensor_2 NUMERIC,
    sensor_3 NUMERIC,
    sensor_4 NUMERIC,
    sensor_5 NUMERIC,
    sensor_6 NUMERIC,
    sensor_7 NUMERIC,
    sensor_8 NUMERIC,
    sensor_9 NUMERIC,
    sensor_10 NUMERIC,
    sensor_11 NUMERIC,
    sensor_12 NUMERIC,
    sensor_13 NUMERIC,
    sensor_14 NUMERIC,
    sensor_15 NUMERIC,
    sensor_16 NUMERIC,
    sensor_17 NUMERIC,
    sensor_18 NUMERIC,
    sensor_19 NUMERIC,
    sensor_20 NUMERIC,
    sensor_21 NUMERIC,
    UNIQUE (SPLIT, DATASET, ENGINE_ID, CYCLE)
);